/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlinevehicleauctionsystem;
/**
 *
 * @author insha
 */

public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    private Mediator mediator;

    public Admin(Mediator mediator) {
        this.mediator = mediator;
    }

    public void sendMessage(String message) {
        mediator.notify(this, message);
    }
    public Admin() {
        initComponents();
    }

    private static class Mediator {

        public Mediator() {
        }

        private void notify(Admin aThis, String message) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnComplain1 = new javax.swing.JButton();
        btnLogout1 = new javax.swing.JButton();
        btnComplain2 = new javax.swing.JButton();
        btnComplain3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ADMINSTRATOR PANEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 490, 40));

        btnComplain1.setBackground(new java.awt.Color(204, 204, 204));
        btnComplain1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnComplain1.setText("COMPLAINS");
        btnComplain1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnComplain1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplain1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComplain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 212, -1));

        btnLogout1.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnLogout1.setText("LOG OUT");
        btnLogout1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 460, 212, -1));

        btnComplain2.setBackground(new java.awt.Color(204, 204, 204));
        btnComplain2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnComplain2.setText("SHOW BIKE");
        btnComplain2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnComplain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplain2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComplain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 212, 30));

        btnComplain3.setBackground(new java.awt.Color(204, 204, 204));
        btnComplain3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnComplain3.setText("SHOW CAR");
        btnComplain3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnComplain3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComplain3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnComplain3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 212, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlinevehicleauctionsystem/auction1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComplain1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplain1ActionPerformed
        setVisible(false);
        AdminComplain ob=new AdminComplain();
        ob.setVisible(true);
    }//GEN-LAST:event_btnComplain1ActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
       setVisible(false);
        Home ob=new Home();
        ob.setVisible(true);
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void btnComplain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplain2ActionPerformed
setVisible(false);
        BikeAuction ob=new BikeAuction();
        ob.setVisible(true);                                       
    }//GEN-LAST:event_btnComplain2ActionPerformed

    private void btnComplain3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComplain3ActionPerformed
        setVisible(false);
        CarAuction ob=new CarAuction();
        ob.setVisible(true);    }//GEN-LAST:event_btnComplain3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplain1;
    private javax.swing.JButton btnComplain2;
    private javax.swing.JButton btnComplain3;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
